### ISSUE TITLE
内容は好きだが、書き方は嫌いのときにどう評価したらよいのか分からない

### ISSUE THREAD

**Issue by kenzan100** [articles-each/articles-each.github.io#2]
内容は好きだが、書き方は嫌い

例えば、最近届いた「C言語でSchemeインタプリタつくった」って記事は
タイトル読む限りでは おっ！
って感じなんですが、記事の構成が、コードの羅列だけで何の解説もなく終わっていて(書きかけ？)、読むのが辛くて途中で諦めました。

**Comment by koher** [comment]
記事の評価基準は、その記事を読んでよかったかどうかでお願い致します。今回のケースでは、記事自体にはネガティブな印象を持たれているようですのでマイナスの評価をして下さい。

現時点では、マイナス評価の影響はその記事のキーワードにかかるのではなく、他の人の評価と比較する際に現れるものです。当該記事をマイナス評価している人とは興味の持ち方が似ている、プラス評価している人とは興味が持ち方が似ていないとスコアリングされ、興味の近い人が高評価している記事が優先的に配信されるようになります。

このあたりの評価基準はわかりづらいと思いますので、何かしらアプリ内で案内できる形にしたいと考えています（特に初回起動時）。

**Comment by kenzan100** [comment]
なるほど、そのように致します。

**Comment by kenzan100** [comment]
コメントありがとうございました！ :smile:
